"""create sales table MVP

Revision ID: 44155cdf0420
Revises: 0a7d8964b298
Create Date: 2025-08-27 20:46:57.361816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44155cdf0420'
down_revision: Union[str, Sequence[str], None] = '0a7d8964b298'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('amount', sa.Float(), nullable=True))
    op.add_column('sales', sa.Column('margin', sa.Float(), nullable=True))
    op.add_column('sales', sa.Column('quantity', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_sales_product'), table_name='sales')
    op.create_index(op.f('ix_sales_date'), 'sales', ['date'], unique=False)
    op.drop_column('sales', 'cost')
    op.drop_column('sales', 'revenue')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('revenue', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('sales', sa.Column('cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_sales_date'), table_name='sales')
    op.create_index(op.f('ix_sales_product'), 'sales', ['product'], unique=False)
    op.drop_column('sales', 'quantity')
    op.drop_column('sales', 'margin')
    op.drop_column('sales', 'amount')
    # ### end Alembic commands ###
